=== CAHIER DES CHARGES DU GAME CONCEPT  ===

==  intitulé du jeu ==
Renseigner chaque catégorie afin de définir votre jeu en générale.
Genre:  éducatif.
Style: Action...
Plate-forme: "PC", mozilla
moteur: Phazer/BabylonJS
Nombre de jouer:  1
pegi : +4 ans x)

== PRINCIPE DE JEU ==
Brève description devant cadrer et donner l'idée de votre concept, en quelques lignes.

Le sport est bon pour la santé x),
Dans une vie d'étudiant, La semaine est toujours aussi bien chargé.
Alors mettons-y un peu de place pour le sport.
Savoir faire son planning est essentiel pour la semaine,
s'organiser donne toujours des bon résultat.
Une fois qu'on sait ce que la semaine nous réserve, plus qu'a la réaliser.
y'allait et sans doute la chose l'a plus simple a faire, mais la plus négliger.
le Sport commence tout jes jours, chaque moment de la journée,
vous pouvez faire du sport.


Descriptif sous forme de liste présentant votre gameplay.
Préparation
- Le joueur choisit son profil de jeu
- difficulté a choisir ( étudiant, vie actif, retraité )
- Un planning a remplir en fonction des cours d'une personne normale
- Lancement du jeu dans la ville. ( mission simple allé a son sport par diffèrent moyen ).

= Action  =
- Spawn dans une ville ( style pokemon)
- choisir sa locomotion,( ex: a pied, vélo , voiture, transport en commun )
- en fonction des sport choisie dans le planning, l'heure et la mission se met a jours,
- se rendre a l'endroit pour faire du sport en parcourant la ville.

= Objectif: Faire du Sport !  =
- Savoir s'organiser un planning.
- Connaitre les sport possible a faire dans une ville.
- Commencer a faire une Activité sportif !
- Organiser avec qui on peux faire du sport !

== INSPIRATION ==
Exemples de jeux existants dans le même esprit ou vous ayant fortement inspirés.
- GTA
- Pokemon
-

=== Source ===
- http://inpes.santepubliquefrance.fr/CFESBases/catalogue/pdf/1177.pdf
-
== POINT-CLES  ==
Citez 3 points-clés qui feront de votre concept un jeu prometteur.
