=== CAHIER DES CHARGES DU GAME CONCEPT  ===

==  intitulé du jeu ==
Renseigner chaque catégorie afin de définir votre jeu en générale.
Genre:  éducatif.
Style: Action...
Plate-forme: "PC", mozilla
moteur: Phazer
Nombre de jouer:  1
pegi : +4 ans x)

== PRINCIPE DE JEU ==
Brève description devant cadrer et donner l'idée de votre concept, en quelques lignes.

blabla....

Descriptif sous forme de liste présentant votre gameplay.
= Préparation =
- Le joueur choisit son profil de jeu
- difficulté a choisir ( sportif du dimanche. . . . sportif de haut niveau )
- Un planning a remplir en fonction des cours d'une personne normale
- Lancement du jeu !

= Action  =
- Spawn dans une ville
- choisir sa locomotion,( ex: a pied, vélo , voiture, transport en commun )
- en fonction des sport choisie dans le planning, l'heure et la mission se met a jours,
- se rendre a l'endroit pour faire du sport en parcourant la ville.

= Objectif: Faire du Sport !  =
- Savoir s'organiser un planning.
- Connaitre les sport possible a faire dans une ville.
- Commencer a faire une Activité sportif !

== INSPIRATION ==
Exemples de jeux existants dans le même esprit ou vous ayant fortement inspirés.
- GTA
-
-

=== Source ===
- http://inpes.santepubliquefrance.fr/CFESBases/catalogue/pdf/1177.pdf
-
== POINT-CLES  ==
Citez 3 points-clés qui feront de votre concept un jeu prometteur.
