=== CAHIER DES CHARGES DU GAME CONCEPT  ===

==  intitulé du jeu ==
Renseigner chaque catégorie afin de définir votre jeu en générale.
Genre:  éducatif.
Style: Action...
Plate-forme: "PC", mozilla
moteur: Phazer
Nombre de jouer:  1
pegi : +4 ans x)

== PRINCIPE DE JEU ==
Brève description devant cadrer et donner l'idée de votre concept, en quelques lignes.

blabla....

Descriptif sous forme de liste présentant votre gameplay.
* Préparation
- Le joueur choisit son profil de jeu
- Lancement du jeu !
* Action
- Spawn dans une ville
-
-
* Objectif: Faire du Sport !
-
-

== INSPIRATION ==
Exemples de jeux existants dans le même esprit ou vous ayant fortement inspirés.
- GTA
-
-

== POINT-CLES  ==
Citez 3 points-clés qui feront de votre concept un jeu prometteur.
