Dans Le Projet vierge, j'ai réaliser une modêle MVC simple pour vous donner l'idée de comment on va séparer les tâche,
car on peu avoir une partie Model qui marche, sans le Controller, donc 2 personne peuvent le réalisé indépendament,
faut juste une structure commun

Projet :

répartition des Tâche:

*Dessins
BOULANOUAR Mohamed
AIOUNE Nasreddine

*Action code fonction
BRUGE Fabien ( généalogie des donné)
DESMARESCAUX Matthieu ( partie action visuelle )
VERRIER Bastien( affichage des caratèristique du personnage )

Faire un planning:
=== 16 février ===


=== 23 février ===


=== Après les vacances ===



Faire un schéma des principale fonctionnalié:
