Test
Dans Le Projet vierge, j'ai réaliser une modêle MVC simple pour vous donner l'idée de comment on va séparer les tâche,
car on peu avoir une partie Model qui marche, sans le Controller, donc 2 personne peuvent le réalisé indépendament,
faut juste une structure commun

Projet :

répartition des Tâche:

*Dessins
BOULANOUAR Mohamed
AIOUNE Nasreddine

*Action code fonction
BRUGE Fabien ( généalogie des donné)
DESMARESCAUX Matthieu ( partie action visuelle )
VERRIER Bastien( affichage des caratèristique du personnage ) => barre de sprint, heure, mission ( ou se rendre activité a faire.)

Faire un planning:
=== 23 février ===
* avancer sur les personnage de base. ( voire pour la ville)
* diffèrencier la partie planning et la ville code ( modèle MVC)

=== Après les vacances ===
* Affiche.
* avoir tout les personnage de prêt.
* avoir un speudo map de ville.
* avoir au moin 1 mission pour tout les niveau.

Faire un schéma des principale fonctionnalié:
voire le Planing.txt
