Dans Le Projet vierge, j'ai réaliser une modêle MVC simple pour vous donner l'idée de comment on va séparer les tâche,
car on peu avoir une partie Model qui marche, sans le Controller, donc 2 personne peuvent le réalisé indépendament,
faut juste une structure commun

Projet :

répartition des Tâche:

*Dessins

*Action parti serveur

*Action parti affichage

Faire un planning:

Faire un schéma des principale fonctionnalié:
